### ISSUE TITLE
Issue with singular vs plural look up

### ISSUE THREAD

**Issue by hallmatt** [svenfuchs/i18n-active_record#145]
Hi! 
I have a site where I have a Contract model. My yml / keys look like this:

```yaml
en:
  activerecord:
    models:
      contract:
        one: Contract
        other: Contracts
```
and
```yaml
es:
  activerecord:
    models:
      contract:
        one: Contract
        other: Contracts
```
When I add a key into the DB table to translate "Contracts" into Spanish (activerecord.models.contract.other), the form submit button breaks

Form Button
` f.button :submit, class: "btn btn-primary"`

Here's the exception:

`translation data {:other=>"Contracts"} can not be used with :count => 1. key 'one' is missing.`

The form button is fixed if I add in the specific translation for the singular key (activerecord.models.contract.one) into the database specifically...even though it should fallback to the yaml file where the key is present.

It seems as if the look up only goes so many layers deep...or assumes the singular version must be present if the plural is as well. Are there certain rules I'm missing or could this be an issue?

Initializer:

```ruby
require 'i18n/backend/active_record'
# https://guides.rubyonrails.org/i18n.html#using-different-backends

if I18n::Backend::ActiveRecord::Translation.table_exists?
  I18n.backend = I18n::Backend::ActiveRecord.new
  I18n::Backend::ActiveRecord.send(:include, I18n::Backend::Memoize)
  I18n::Backend::Simple.send(:include, I18n::Backend::Memoize)
  I18n::Backend::Simple.send(:include, I18n::Backend::Pluralization)
  # I18n::Backend::Chain.send(:include, I18n::Backend::ActiveRecord::Missing)

  # I18n.backend = I18n::Backend::Chain.new(I18n::Backend::Simple.new, I18n.backend) # check YAML first, DB fallback
  I18n.backend = I18n::Backend::Chain.new(I18n.backend, I18n::Backend::Simple.new) # check DB first, YAML fallback
end
```
