### ISSUE TITLE
After upgrade to Rails 7.1, translations that end in a colon return a Hash, not a String

### ISSUE THREAD

**Issue by floydj** [svenfuchs/i18n-active_record#147]
I'm trying to upgrade a Rails 7 app to 7.1, but running into issues with I18n translations.

Given the following translation:

```yaml
[12] pry(main)> Translation.last
=> #<Translation:0x00000001183f0b60
 id: 118058,
 locale: "en",
 key: "project_customer_name",
 value: "Customer's Company Name:",
 interpolations: nil,
 is_proc: false,
 created_at: Mon, 22 Jan 2024 14:37:05.000000000 UTC +00:00,
 updated_at: Mon, 22 Jan 2024 15:00:36.000000000 UTC +00:00>
```

And trying to use that in my view:

```erb
<p><%= t(:project_customer_name) %></p>
```

I'll always get a hash in the resulting HTML, rather than the String I expect:

`{"Customer's Company Name"=>nil}`

Translation occurs properly in any of the following conditions:
* Adding the translation to the `en.yml` file AND removing it from the translations table
* Downgrading back to Rails 7.0
* Removing `i18n.-active_record` (not a long-term option for this project, but tried it for testing)
* Removing the colon from the *end* of the translated value. e.g. "Customer's Company Name"
* Moving the colon anywhere else in the value e.g. "Customer's Company: Name"

About the app:
* Rails 7.1.3
* Ruby 3.2.2

I have tried creating a brand-new Rails 7.1 app with i18n-active_record and...the translation works fine, even with the colon at the end of a value. So it seems there is *something* in my app causing this, but I'm stuck, unsure of how or what to debug further.

Any idea what's going on or how I can troubleshoot further?  Appreciate the help!
